import type { Movie } from "./types"

export const moviesData: Movie[] = [
  // Updated movies with real poster images
  {
    id: "1",
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DARKKNIGHT.jpg-atevVybyWzNa3ouGotef42iZCwHHkW.jpeg",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: 152,
    releaseYear: 2008,
    genre: ["Action", "Crime", "Drama", "Blockbuster"],
    language: "English",
    rating: 9.0,
    featured: true,
    isStreaming: true,
    dateAdded: new Date("2024-12-01"),
  },
  {
    id: "2",
    title: "Inception",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Inception.jpg-8FCzYwIkI0X2HxufGPEmajGzqxlWWd.jpeg",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: 148,
    releaseYear: 2010,
    genre: ["Action", "Sci-Fi", "Thriller", "Blockbuster"],
    language: "English",
    rating: 8.8,
    featured: true,
    isStreaming: true,
    dateAdded: new Date("2024-12-05"),
  },
  {
    id: "3",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Interstellar-Sps1OkZQlBB8ckQ9kClyaVQ0RdJU4O.webp",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    duration: 169,
    releaseYear: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi", "Blockbuster"],
    language: "English",
    rating: 8.6,
    featured: false,
    isStreaming: false,
    dateAdded: new Date("2024-11-15"),
  },
  {
    id: "4",
    title: "The Matrix",
    description:
      "A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.",
    poster: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/the_matrix-53q9LdHscg77sLnygVMQWZvjbKXsov.webp",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    duration: 136,
    releaseYear: 1999,
    genre: ["Action", "Sci-Fi", "Classic"],
    language: "English",
    rating: 8.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-20"),
  },
  {
    id: "5",
    title: "Pulp Fiction",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    duration: 154,
    releaseYear: 1994,
    genre: ["Crime", "Drama", "Classic"],
    language: "English",
    rating: 8.9,
    featured: false,
    isStreaming: false,
    dateAdded: new Date("2024-10-10"),
  },
  {
    id: "6",
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    duration: 142,
    releaseYear: 1994,
    genre: ["Drama", "Classic"],
    language: "English",
    rating: 9.3,
    featured: true,
    isStreaming: true,
    dateAdded: new Date("2024-11-25"),
  },
  {
    id: "7",
    title: "The Godfather",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    duration: 175,
    releaseYear: 1972,
    genre: ["Crime", "Drama", "Classic"],
    language: "English",
    rating: 9.2,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-10-05"),
  },
  {
    id: "8",
    title: "Parasite",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    duration: 132,
    releaseYear: 2019,
    genre: ["Comedy", "Drama", "Thriller", "International", "K-Drama"],
    language: "Korean",
    rating: 8.6,
    featured: true,
    isStreaming: true,
    dateAdded: new Date("2025-05-25"),
  },
  {
    id: "9",
    title: "Spirited Away",
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    duration: 125,
    releaseYear: 2001,
    genre: ["Animation", "Adventure", "Family", "Kids & Family", "Japanese", "Anime"],
    language: "Japanese",
    rating: 8.6,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-05-28"),
  },
  {
    id: "10",
    title: "The Silence of the Lambs",
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    duration: 118,
    releaseYear: 1991,
    genre: ["Crime", "Drama", "Thriller", "Horror", "Classic"],
    language: "English",
    rating: 8.6,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-10"),
  },

  // New movies for specific categories
  {
    id: "11",
    title: "Frozen",
    description:
      "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    duration: 102,
    releaseYear: 2013,
    genre: ["Animation", "Adventure", "Comedy", "Family", "Kids & Family"],
    language: "English",
    rating: 7.4,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-05-30"),
  },
  {
    id: "12",
    title: "Toy Story 4",
    description:
      "When a new toy called 'Forky' joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    duration: 100,
    releaseYear: 2019,
    genre: ["Animation", "Adventure", "Comedy", "Family", "Kids & Family"],
    language: "English",
    rating: 7.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-05-31"),
  },
  {
    id: "13",
    title: "My Neighbor Totoro",
    description:
      "When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    duration: 86,
    releaseYear: 1988,
    genre: ["Animation", "Family", "Kids & Family", "Japanese", "Anime"],
    language: "Japanese",
    rating: 8.2,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-06-01"),
  },
  {
    id: "14",
    title: "Attack on Titan: The Final Season",
    description:
      "Eren Jaeger and his friends join the fight against the Titans after their home town is invaded by the Colossal Titan.",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Attack%20on%20Titan-%20The%20Final%20Season.jpg-grgF3jJmDK0dmy4NQKP93WhxqqdtRa.jpeg",
    backdrop:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attack-on-titan-the-final-season-1920-x-1080-wallpaper-mf9hmc77oa2utphx.jpg-8PSmm1do3pEKyqyH1JbQdx57u29dy6.jpeg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: 24,
    releaseYear: 2020,
    genre: ["Animation", "Action", "Drama", "Anime", "TV Show"],
    language: "Japanese",
    rating: 9.0,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-06-02"),
  },
  {
    id: "15",
    title: "Demon Slayer: Mugen Train",
    description:
      "Tanjiro and his friends accompany the Flame Hashira Kyojuro Rengoku to investigate a mysterious series of disappearances occurring inside a train.",
    poster:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Demon%20Slayer-%20Mugen%20Train.jpg-1quRqq9khA7sl0kiRFhvUJTK54318t.jpeg",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: 117,
    releaseYear: 2020,
    genre: ["Animation", "Action", "Adventure", "Anime", "Japanese"],
    language: "Japanese",
    rating: 8.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2025-06-02"),
  },
  {
    id: "16",
    title: "Squid Game",
    description:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    duration: 60,
    releaseYear: 2021,
    genre: ["Drama", "Thriller", "K-Drama", "TV Show"],
    language: "Korean",
    rating: 8.0,
    featured: true,
    isStreaming: true,
    dateAdded: new Date("2024-12-10"),
  },
  {
    id: "17",
    title: "Crash Landing on You",
    description:
      "A paragliding mishap drops a South Korean heiress in North Korea -- and into the life of an army officer, who decides he will help her hide.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    duration: 70,
    releaseYear: 2019,
    genre: ["Comedy", "Drama", "Romance", "K-Drama", "TV Show"],
    language: "Korean",
    rating: 8.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-30"),
  },
  {
    id: "18",
    title: "The Grand Budapest Hotel",
    description:
      "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    duration: 99,
    releaseYear: 2014,
    genre: ["Adventure", "Comedy", "Crime"],
    language: "English",
    rating: 8.1,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-05"),
  },
  {
    id: "19",
    title: "Superbad",
    description:
      "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    duration: 113,
    releaseYear: 2007,
    genre: ["Comedy"],
    language: "English",
    rating: 7.6,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-10-20"),
  },
  {
    id: "20",
    title: "The Hangover",
    description:
      "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    duration: 100,
    releaseYear: 2009,
    genre: ["Comedy"],
    language: "English",
    rating: 7.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-10-15"),
  },
  {
    id: "21",
    title: "Your Name",
    description:
      "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    duration: 106,
    releaseYear: 2016,
    genre: ["Animation", "Drama", "Fantasy", "Romance", "Japanese", "Anime"],
    language: "Japanese",
    rating: 8.4,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-12-15"),
  },
  {
    id: "22",
    title: "Akira",
    description:
      "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    duration: 124,
    releaseYear: 1988,
    genre: ["Animation", "Action", "Drama", "Sci-Fi", "Japanese", "Anime", "Classic"],
    language: "Japanese",
    rating: 8.0,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-09-20"),
  },
  {
    id: "23",
    title: "Avengers: Endgame",
    description:
      "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    duration: 181,
    releaseYear: 2019,
    genre: ["Action", "Adventure", "Drama", "Blockbuster"],
    language: "English",
    rating: 8.4,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-12-20"),
  },
  {
    id: "24",
    title: "Stranger Things",
    description:
      "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    duration: 50,
    releaseYear: 2016,
    genre: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller", "TV Show"],
    language: "English",
    rating: 8.7,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-28"),
  },
  {
    id: "25",
    title: "The Office",
    description:
      "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    duration: 22,
    releaseYear: 2005,
    genre: ["Comedy", "TV Show"],
    language: "English",
    rating: 8.9,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-09-10"),
  },
  {
    id: "26",
    title: "Seven Samurai",
    description:
      "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    duration: 207,
    releaseYear: 1954,
    genre: ["Action", "Adventure", "Drama", "Japanese", "Classic"],
    language: "Japanese",
    rating: 8.6,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-08-15"),
  },
  {
    id: "27",
    title: "The Conjuring",
    description:
      "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: 112,
    releaseYear: 2013,
    genre: ["Horror", "Mystery", "Thriller"],
    language: "English",
    rating: 7.5,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-10-25"),
  },
  {
    id: "28",
    title: "La La Land",
    description:
      "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: 128,
    releaseYear: 2016,
    genre: ["Comedy", "Drama", "Music", "Romance"],
    language: "English",
    rating: 8.0,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-11-12"),
  },
  {
    id: "29",
    title: "Coco",
    description:
      "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    duration: 105,
    releaseYear: 2017,
    genre: ["Animation", "Adventure", "Family", "Fantasy", "Music", "Kids & Family"],
    language: "English",
    rating: 8.4,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-12-25"),
  },
  {
    id: "30",
    title: "Kingdom",
    description:
      "While strange rumors about their ill King grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    duration: 60,
    releaseYear: 2019,
    genre: ["Action", "Drama", "Horror", "Thriller", "K-Drama", "TV Show"],
    language: "Korean",
    rating: 8.3,
    featured: false,
    isStreaming: true,
    dateAdded: new Date("2024-12-28"),
  },

  // Additional new movies (some not streaming by default)
  {
    id: "31",
    title: "Dune",
    description:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    duration: 155,
    releaseYear: 2021,
    genre: ["Action", "Adventure", "Drama", "Sci-Fi", "Blockbuster"],
    language: "English",
    rating: 8.0,
    featured: false,
    isStreaming: false, // Not streaming by default
    dateAdded: new Date("2024-12-30"),
  },
  {
    id: "32",
    title: "Spider-Man: No Way Home",
    description:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    duration: 148,
    releaseYear: 2021,
    genre: ["Action", "Adventure", "Fantasy", "Blockbuster"],
    language: "English",
    rating: 8.4,
    featured: false,
    isStreaming: false, // Not streaming by default
    dateAdded: new Date("2025-01-01"),
  },
  {
    id: "33",
    title: "Top Gun: Maverick",
    description:
      "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    duration: 130,
    releaseYear: 2022,
    genre: ["Action", "Drama", "Blockbuster"],
    language: "English",
    rating: 8.3,
    featured: false,
    isStreaming: false, // Not streaming by default
    dateAdded: new Date("2025-01-05"),
  },
  {
    id: "34",
    title: "Everything Everywhere All at Once",
    description:
      "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    duration: 139,
    releaseYear: 2022,
    genre: ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Sci-Fi"],
    language: "English",
    rating: 7.8,
    featured: false,
    isStreaming: false, // Not streaming by default
    dateAdded: new Date("2025-01-10"),
  },
  {
    id: "35",
    title: "The Batman",
    description:
      "When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=720&width=1280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    duration: 176,
    releaseYear: 2022,
    genre: ["Action", "Crime", "Drama", "Mystery", "Thriller", "Blockbuster"],
    language: "English",
    rating: 7.8,
    featured: false,
    isStreaming: false, // Not streaming by default
    dateAdded: new Date("2025-01-15"),
  },
]
